### ISSUE TITLE
[Broken] Trovo.live no longer works

### ISSUE THREAD

**Issue by GUUser91** [yt-dlp/yt-dlp#139]
## Checklist

- [✓] I'm reporting a broken site support
- [✓] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [✓] I've checked that all provided URLs are alive and playable in a browser
- [✓] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [✓] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v https://trovo.live/video/ltv-100651463_100651463_1614372839?ltab=videos
[debug] Command-line config: ['-v', 'https://trovo.live/video/ltv-100651463_100651463_1614372839?ltab=videos']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.03.2 
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[TrovoVod] ltv-100651463_100651463_1614372839: Downloading JSON metadata
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 720P
[debug] Invoking downloader on 'http://vod.trovo.live/6ae21848vodger1301120758/fb0a08765285890814364419389/playlist_eof.m3u8?t=60415453&us=ChxrODVzVUhKemYyMi9KR1A1Y2hrRTRvYlFNUWc9EiRmNzlmZTg3NC05NzQ1LTQ0NjYtYTEzMS1kNGIxNmE3MWNkYTEaImx0di0xMDA2NTE0NjNfMTAwNjUxNDYzXzE2MTQzNzI4Mzkg8_-DggY4xBNCDTcwLjEzMy4xNzcuNjBKJlZvZFJlYWRlclNlcnZpY2VfQmF0Y2hHZXRWb2REZXRhaWxJbmZvUARgAw&sign=2b89f281f47fbcc266d1403a40c8c768'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2381, in process_info
    success, real_download = dl(temp_filename, info_dict)
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2142, in dl
    return fd.download(name, info, subtitle)
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 375, in download
    return self.real_download(filename, info_dict), True
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/downloader/hls.py", line 67, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/home/bud/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2784, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

## Description

WRITE DESCRIPTION HERE

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/28346

Seems the website has made some changes

**Comment by pukkandan** [comment]
oh, looks like it was fixed upstream too... well, no matter

**Comment by velcroskids3** [comment]
Has this been fixed? For both yt-dlp and youtube-dl I have downloaded their respective Trovo py files overwriting the old ones and I still get 403 Forbidden error and no video was downloaded or saved.
Did I update the fix correctly?

**Comment by tagwich** [comment]
Has this been fixed? For both yt-dlp and youtube-dl I have downloaded their respective Trovo py files overwriting the old ones and I still get 403 Forbidden error and no video was downloaded or saved.
Did I update the fix correctly?

**Comment by tagwich** [comment]
thank you for yt-dlp-2021.03.07 -- it works!

**Comment by tagwich** [comment]
**thank you** for yt-dlp-2021.03.07 -- it's fixed!
