### ISSUE TITLE
southpark.de Module downloads video fragments and does not concatenate split parts afterwards

### ISSUE THREAD

**Issue by ThisLimn0** [yt-dlp/yt-dlp#1465]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello, when downloading with the latest version of yt-dlp from the website southpark.de it downloads split fragments of an episode, not the whole episode in one file.

Test: https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9 

### Verbose log

```shell
C:\Users\N0>yt-dlp.exe https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9 -Uv -f best
[debug] Command-line config: ['https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9', '-Uv', '-f', 'best']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [southpark.de] Extracting URL: https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9
[southpark.de] south-park-eine-hohle-bar-staffel-16-ep-9: Downloading webpage
[southpark.de] c541c989-b10c-4ef8-9dbc-66000eff7bcd: Downloading JSON metadata
[southpark.de] c541c989-b10c-4ef8-9dbc-66000eff7bcd: Downloading info
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Extracting information
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading video urls
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Extracting information
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Downloading video urls
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Extracting information
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading video urls
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Extracting information
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading video urls
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Extracting information
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading video urls
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Eine hohle Bar
[southpark.de] playlist Eine hohle Bar: Collected 5 videos; downloading 5 of them
[download] Downloading video 1 of 5
[info] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading 1 format(s): hls-4405
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/52/2127f8f5639e4fa0b2a5d63af8e9bc0d/892197/0/stream_1920x1080_4326757_1302799876.m3u8?tk=st=1635447035~exp=1635461435~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/52/2127f8f5639e4fa0b2a5d63af8e9bc0d/892197/0/stream_1920x1080_4326757_1302799876.m3u8*~hmac=678fcbe582c0947373702911b0273a92e5e62e87042af0c030d687cbb6dc8cda&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 6
[download] Destination: South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S1 [972ac71a-e1d7-4269-9497-556b8598842c].mp4
[download] 100% of 16.82MiB in 00:04
[debug] ffmpeg command line: ffprobe -show_streams "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S1 [972ac71a-e1d7-4269-9497-556b8598842c].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S1 [972ac71a-e1d7-4269-9497-556b8598842c].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S1 [972ac71a-e1d7-4269-9497-556b8598842c].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S1 [972ac71a-e1d7-4269-9497-556b8598842c].temp.mp4"
[download] Downloading video 2 of 5
[info] d71b0700-6e45-4afc-a851-672d690783ac: Downloading 1 format(s): hls-2616
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/54/9ecd1d10639040e58d8228bac2ebd8b9/892211/0/stream_1920x1080_2511683_3326696966.m3u8?tk=st=1635447534~exp=1635461934~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/54/9ecd1d10639040e58d8228bac2ebd8b9/892211/0/stream_1920x1080_2511683_3326696966.m3u8*~hmac=6d54c05a860e322a5f66762f00279e80090d56df44799c5c8f3d4aec0ca75b34&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 101
[download] Destination: South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S2 [d71b0700-6e45-4afc-a851-672d690783ac].mp4
[download] 100% of 187.95MiB in 00:45
[debug] ffmpeg command line: ffprobe -show_streams "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S2 [d71b0700-6e45-4afc-a851-672d690783ac].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S2 [d71b0700-6e45-4afc-a851-672d690783ac].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S2 [d71b0700-6e45-4afc-a851-672d690783ac].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S2 [d71b0700-6e45-4afc-a851-672d690783ac].temp.mp4"
[download] Downloading video 3 of 5
[info] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading 1 format(s): hls-3020
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/55/24916b5a1a404c2780f03a422db096ed/892213/0/stream_1920x1080_2905996_2208735639.m3u8?tk=st=1635447190~exp=1635461590~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/55/24916b5a1a404c2780f03a422db096ed/892213/0/stream_1920x1080_2905996_2208735639.m3u8*~hmac=f3629499a5d5cd81d879881c67661fefefff8a252f5c3fbde5115245555e52c7&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 69
[download] Destination: South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S3 [514f18a2-3618-4039-9cda-6ff36c81f909].mp4
[download] 100% of 147.36MiB in 00:35
[debug] ffmpeg command line: ffprobe -show_streams "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S3 [514f18a2-3618-4039-9cda-6ff36c81f909].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S3 [514f18a2-3618-4039-9cda-6ff36c81f909].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S3 [514f18a2-3618-4039-9cda-6ff36c81f909].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S3 [514f18a2-3618-4039-9cda-6ff36c81f909].temp.mp4"
[download] Downloading video 4 of 5
[info] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading 1 format(s): hls-3154
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/56/9c53e9ea902f4ec38870e5ed39cf08a0/892220/0/stream_1920x1080_3037696_2395139568.m3u8?tk=st=1635446055~exp=1635460455~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/56/9c53e9ea902f4ec38870e5ed39cf08a0/892220/0/stream_1920x1080_3037696_2395139568.m3u8*~hmac=c1cdbcef0c171ecd8201c24aeb5ff0ab824ed1421ad226d03bba0317bd647d8d&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 44
[download] Destination: South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S4 [4cdd49af-6283-4494-ba6c-3dd1cb2fb83f].mp4
[download] 100% of 98.17MiB in 00:22
[debug] ffmpeg command line: ffprobe -show_streams "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S4 [4cdd49af-6283-4494-ba6c-3dd1cb2fb83f].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S4 [4cdd49af-6283-4494-ba6c-3dd1cb2fb83f].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S4 [4cdd49af-6283-4494-ba6c-3dd1cb2fb83f].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S4 [4cdd49af-6283-4494-ba6c-3dd1cb2fb83f].temp.mp4"
[download] Downloading video 5 of 5
[info] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading 1 format(s): hls-2239
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/57/6866bb96f32f454a8120bb5e7e236139/892221/0/stream_1920x1080_2139253_2712790664.m3u8?tk=st=1635449431~exp=1635463831~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/57/6866bb96f32f454a8120bb5e7e236139/892221/0/stream_1920x1080_2139253_2712790664.m3u8*~hmac=28aa2aff21a3ca2783f4380dfe6f1a55c1d6505d3a9bc42bbf4c0de92ca08b1a&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3
[download] Destination: South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S5 [3f100aa3-85c8-4c78-97b9-8641db198a6d].mp4
[download] 100% of 4.00MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S5 [3f100aa3-85c8-4c78-97b9-8641db198a6d].mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S5 [3f100aa3-85c8-4c78-97b9-8641db198a6d].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S5 [3f100aa3-85c8-4c78-97b9-8641db198a6d].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:South Park _ Raising The Bar _ E 1609 _ HDSS1609P deu _ Version - 509595 _ Comedy Central S5 [3f100aa3-85c8-4c78-97b9-8641db198a6d].temp.mp4"
[download] Finished downloading playlist: Eine hohle Bar
```

**Comment by ThisLimn0** [comment]
> Most likely, it is a `multi_video` and would require something like [ytdl-org/youtube-dl#28153](https://github.com/ytdl-org/youtube-dl/pull/28153). But I cant currently test due to geo-restriction

Hat shall i supply for you to fix the bug?`I am not fluent in python al all.

**Comment by ThisLimn0** [comment]
Okay, it seems that i have found a temporary workaround to download a full episode. It does not work for every episode however. Using the arguments `--compat-options multistreams -o "S%(season_number)s-E%(episode_number)s.%(ext)s"`

Verbose Log (for not working episode):
`C:\Users\N0>yt-dlp.exe https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9 --compat-options multistreams -o "S%(season_number)s-E%(episode_number)s.%(ext)s" -Uv
[debug] Command-line config: ['https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9', '--compat-options', 'multistreams', '-o', 'S%(season_number)s-E%(episode_number)s.%(ext)s', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Compatibility options: multistreams
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [southpark.de] Extracting URL: https://www.southpark.de/folgen/egyait/south-park-eine-hohle-bar-staffel-16-ep-9
[southpark.de] south-park-eine-hohle-bar-staffel-16-ep-9: Downloading webpage
[southpark.de] c541c989-b10c-4ef8-9dbc-66000eff7bcd: Downloading JSON metadata
[southpark.de] c541c989-b10c-4ef8-9dbc-66000eff7bcd: Downloading info
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Extracting information
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading video urls
[southpark.de] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Extracting information
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Downloading video urls
[southpark.de] d71b0700-6e45-4afc-a851-672d690783ac: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Extracting information
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading video urls
[southpark.de] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Extracting information
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading video urls
[southpark.de] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Extracting information
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading video urls
[southpark.de] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Eine hohle Bar
[southpark.de] playlist Eine hohle Bar: Collected 5 videos; downloading 5 of them
[download] Downloading video 1 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[info] 972ac71a-e1d7-4269-9497-556b8598842c: Downloading 1 format(s): hls-4405
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/52/2127f8f5639e4fa0b2a5d63af8e9bc0d/892197/0/stream_1920x1080_4326757_1302799876.m3u8?tk=st=1635797065~exp=1635811465~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/52/2127f8f5639e4fa0b2a5d63af8e9bc0d/892197/0/stream_1920x1080_4326757_1302799876.m3u8*~hmac=482decf0ee403eb3f9ceba53a2543a8934920ece54a72755d68f6a49093d18e4&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 6
[download] Destination: S16-E9.mp4
[download] 100% of 16.82MiB in 00:04
[debug] ffmpeg command line: ffprobe -show_streams "file:S16-E9.mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "S16-E9.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:S16-E9.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:S16-E9.temp.mp4"
[download] Downloading video 2 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[info] d71b0700-6e45-4afc-a851-672d690783ac: Downloading 1 format(s): hls-2616
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/54/9ecd1d10639040e58d8228bac2ebd8b9/892211/0/stream_1920x1080_2511683_3326696966.m3u8?tk=st=1635798782~exp=1635813182~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/54/9ecd1d10639040e58d8228bac2ebd8b9/892211/0/stream_1920x1080_2511683_3326696966.m3u8*~hmac=36c66db4ccc59ef6e389255c815a8e033e77bb8ec767c8bba6c0f22af947212e&account=intl.mtvi.com&cdn=ns1"
[download] S16-E9.mp4 has already been downloaded
[download] 100% of 16.30MiBWARNING: d71b0700-6e45-4afc-a851-672d690783ac: malformed AAC bitstream detected
[download] Downloading video 3 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[info] 514f18a2-3618-4039-9cda-6ff36c81f909: Downloading 1 format(s): hls-3020
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/55/24916b5a1a404c2780f03a422db096ed/892213/0/stream_1920x1080_2905996_2208735639.m3u8?tk=st=1635796921~exp=1635811321~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/55/24916b5a1a404c2780f03a422db096ed/892213/0/stream_1920x1080_2905996_2208735639.m3u8*~hmac=9032b7413389ddbd076bf2d39e73a19a020f2824810937094a110b0af60e65ea&account=intl.mtvi.com&cdn=ns1"
[download] S16-E9.mp4 has already been downloaded
[download] 100% of 16.30MiBWARNING: 514f18a2-3618-4039-9cda-6ff36c81f909: malformed AAC bitstream detected
[download] Downloading video 4 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[info] 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: Downloading 1 format(s): hls-3154
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/56/9c53e9ea902f4ec38870e5ed39cf08a0/892220/0/stream_1920x1080_3037696_2395139568.m3u8?tk=st=1635799698~exp=1635814098~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/56/9c53e9ea902f4ec38870e5ed39cf08a0/892220/0/stream_1920x1080_3037696_2395139568.m3u8*~hmac=a9f486e2af7dbe3cc0523fca5852c78be90a17f3911867b15d827b13733d5481&account=intl.mtvi.com&cdn=ns1"
[download] S16-E9.mp4 has already been downloaded
[download] 100% of 16.30MiBWARNING: 4cdd49af-6283-4494-ba6c-3dd1cb2fb83f: malformed AAC bitstream detected
[download] Downloading video 5 of 5
[debug] Default format spec: bestvideo+bestaudio/best
[info] 3f100aa3-85c8-4c78-97b9-8641db198a6d: Downloading 1 format(s): hls-2239
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/57/6866bb96f32f454a8120bb5e7e236139/892221/0/stream_1920x1080_2139253_2712790664.m3u8?tk=st=1635799960~exp=1635814360~acl=/api/playlist/v1/gsp.alias/mediabus/2020/05/06/08/42/57/6866bb96f32f454a8120bb5e7e236139/892221/0/stream_1920x1080_2139253_2712790664.m3u8*~hmac=acd6ed796b0ee6552b91e8758c341d49fe4887a95cd95d890a176383498afcec&account=intl.mtvi.com&cdn=ns1"
[download] S16-E9.mp4 has already been downloaded
[download] 100% of 16.30MiBWARNING: 3f100aa3-85c8-4c78-97b9-8641db198a6d: malformed AAC bitstream detected
[download] Finished downloading playlist: Eine hohle Bar`

Verbose Log (for working episode):
`C:\Users\N0>yt-dlp.exe https://www.southpark.de/folgen/yy0vjs/south-park-das-pandemie-special-staffel-24-ep-1 --compat-options multistreams -o "S%(season_number)s-E%(episode_number)s.%(ext)s" -Uv
[debug] Command-line config: ['https://www.southpark.de/folgen/yy0vjs/south-park-das-pandemie-special-staffel-24-ep-1', '--compat-options', 'multistreams', '-o', 'S%(season_number)s-E%(episode_number)s.%(ext)s', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Compatibility options: multistreams
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [southpark.de] Extracting URL: https://www.southpark.de/folgen/yy0vjs/south-park-das-pandemie-special-staffel-24-ep-1
[southpark.de] south-park-das-pandemie-special-staffel-24-ep-1: Downloading webpage
[southpark.de] 230a4f02-f583-11ea-834d-70df2f866ace: Downloading JSON metadata
[southpark.de] 230a4f02-f583-11ea-834d-70df2f866ace: Downloading info
[southpark.de] d514e26e-2d28-11ec-9b1b-0e40cf2fc285: Extracting information
[southpark.de] d514e26e-2d28-11ec-9b1b-0e40cf2fc285: Downloading video urls
[southpark.de] d514e26e-2d28-11ec-9b1b-0e40cf2fc285: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Das Pandemie-Special
[southpark.de] playlist Das Pandemie-Special: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[info] d514e26e-2d28-11ec-9b1b-0e40cf2fc285: Downloading 1 format(s): hls-2879
[debug] Invoking downloader on "https://dlvrsvc.mtvnservices.com/api/playlist/v1/gsp.won-arc-intl/intlod/won-intl/south_park/south_park_24/2401_south_park_2401/GEG251983/0/stream_1920x1080_2770250_4056068719.m3u8?tk=st=1635798501~exp=1635812901~acl=/api/playlist/v1/gsp.won-arc-intl/intlod/won-intl/south_park/south_park_24/2401_south_park_2401/GEG251983/0/stream_1920x1080_2770250_4056068719.m3u8*~hmac=d8b3f996d837e2500baf2ef34711751c745a6cb8b32526d7ea68cc9e754a39c4&account=intl.mtvi.com&cdn=ns1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 455
[download] Destination: S24-E1.mp4
[download] 100% of 935.21MiB in 04:31
[debug] ffmpeg command line: ffprobe -show_streams "file:S24-E1.mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "S24-E1.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:S24-E1.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:S24-E1.temp.mp4"
[download] Finished downloading playlist: Das Pandemie-Special`

It is really really weird.

**Comment by ThisLimn0** [comment]
Workaround script for Windows users: [https://github.com/ThisLimn0/SouthParkDownloadHelper](https://github.com/ThisLimn0/SouthParkDownloadHelper), concatenates the episodes with ffmpeg, lossless.

**Comment by ThisLimn0** [comment]
Any updates yet?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/3b603dbdf139efe187f961dbe8b1b24ba16ae194 should fix this

**Comment by Scrooge200FES** [comment]
I'm still having this issue on the latest version (2022.04.08). I tested with https://southpark.cc.com/es/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2 and https://www.southpark.de/full-episodes/s21e02-put-it-down.

I end up with five separate video files, with the ad breaks splitting them up (named "Put It Down S1 [7c45fe5a-ca13-467e-b17f-8d59b220f00c]", "Put It Down S2 [66560acc-b72e-4f06-be62-4a98f0c2cda1]", etc.)

If I run this with a "--concat-playlist always" parameter, it downloads them as normal, but towards the end:

> [download] Destination: Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4
[download] 100% of 2.65MiB in 00:03
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Put It Down S5 [a0270ab5-fbe7-495c-a305-eea9374b0205].mp4"
ERROR: Concatenation is not supported when downloading multiple separate formats
