### ISSUE TITLE
Unable to download unlisted videos from Vimeo

### ISSUE THREAD

**Issue by TaktakTaktouk** [yt-dlp/yt-dlp#1471]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Description

I can no longer download some videos from Vimeo.  They are unlisted from the same channel. 

### Verbose log

```shell
yt-dlp https://vimeo.com/605084509/3752607502 -v
[debug] Command-line config: ['https://vimeo.com/605084509/3752607502', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.9.0 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/605084509/3752607502
[vimeo] 3752607502: Downloading webpage
[vimeo] 3752607502: Downloading JSON metadata
[vimeo] 3752607502: Downloading JSON metadata
ERROR: [vimeo] 3752607502: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 702, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3252, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by TheTechRobo** [comment]
Same issue. Unlisted **live event**. Tried with both without `event` and replacing `event` with `videos`

```
themandownstairs:~/s/VIMEO_IS_FUCKING_TRASH ❯❯❯ yt-dlp --continue --retries 4  --ignore-errors -f bestvideo+bestaudio --verbose https://vimeo.com/event/1472519/20f628b58a
[debug] Command-line config: ['--continue', '--retries', '4', '--ignore-errors', '-f', 'bestvideo+bestaudio', '--verbose', 'https://vimeo.com/event/1472519/20f628b58a']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.10.0-0.bpo.5-amd64-x86_64-with-glibc2.28
[debug] exe versions: ffmpeg 4.1.8, ffprobe 4.1.8                              
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets   
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/event/1472519/20f628b58a     
[vimeo] 1472519: Downloading JSON metadata                                     
[vimeo] 1472519: Downloading JSON metadata                                     
ERROR: [vimeo] 1472519: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.                             
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 702, in _request_webpage
    return self._downloader.urlopen(url_or_request)                            
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3252, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)                
  File "/opt/python-3.9.7/lib/python3.9/urllib/request.py", line 523, in open  
    response = meth(req, response)
  File "/opt/python-3.9.7/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python-3.9.7/lib/python3.9/urllib/request.py", line 561, in error 
    return self._call_chain(*args)
  File "/opt/python-3.9.7/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python-3.9.7/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)                         

themandownstairs:~/s/VIMEO_IS_FUCKING_TRASH ❯❯❯ yt-dlp --version              1
2021.10.22
```

**Comment by pukkandan** [comment]
was fixed in https://github.com/yt-dlp/yt-dlp/commit/2a6f8475acfc782c36933332cc4bf31a37a5278c
idk why github didn't close it

**Comment by TheTechRobo** [comment]
After fully uninstalling and then installing from git+https://github.com/yt-dlp/yt-dlp, my issue persists.

**Comment by pukkandan** [comment]
The issue that was originally reported here has been fixed. 

Your problem seems different. Vimeo events are not supported currently afaik. You will have to open a site-feature request for it

**Comment by TheTechRobo** [comment]
OK, I'll make a new issue
