### ISSUE TITLE
--live-from-start didn't merge after live stream end.

### ISSUE THREAD

**Issue by JC-Chung** [yt-dlp/yt-dlp#2137]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I use `yt-dlp -o "[%(upload_date)s]%(title)s-%(id)s.%(ext)s" --live-from-start --write-thumbnail --write-description --write-info-json --ignore-no-format "https://www.youtube.com/watch?v=videoID"` to download `Dji-ehIz5_k` and `Z3tKCt3PbOg`.
It works well in the start but when the live stream end,
it retry the next second and return `ERROR: Did not get any data blocks`.
In the end show `ERROR: unable to download video data: [Errno 2] No such file or directory:` then end the program.

### Verbose log

```shell
yt-dlp -Uv -o "[%(upload_date)s]%(title)s-%(id)s.%(ext)s" --live-from-start --write-thumbnail --write-description --write-info-json --ignore-no-format "https://www.youtube.com/watch?v=Dji-ehIz5_k"
[debug] Command-line config: ['-Uv', '-o', '[%(upload_date)s]%(title)s-%(id)s.%(ext)s', '--live-from-start', '--write-thumbnail', '--write-description', '--write-info-json', '--ignore-no-format', 'https://www.youtube.com/watch?v=Dji-ehIz5_k']
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Dji-ehIz5_k
[youtube] Dji-ehIz5_k: Downloading webpage
[youtube] Dji-ehIz5_k: Downloading android player API JSON
[debug] Loading youtube-nsig.8da38e9a from cache
[debug] [youtube] Decrypted nsig ycT2-H23UUD5mDyM => I9Gs9msLHbATpQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Dji-ehIz5_k: Downloading 1 format(s): 303+251
[info] Writing video description to: [20211227]【#天音かなた2周年LIVE】3D LIVE 「リベンジ」_ Amane Kanata 3DLIVE 'Revenge'【天音かなた_ホロライブ】-Dji-ehIz5_k.description
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: [20211227]【#天音かなた2周年LIVE】3D LIVE 「リベンジ」_ Amane Kanata 3DLIVE 'Revenge'【天音かなた_ホロライブ】-Dji-ehIz5_k.webp
[info] Writing video metadata as JSON to: [20211227]【#天音かなた2周年LIVE】3D LIVE 「リベンジ」_ Amane Kanata 3DLIVE 'Revenge'【天音かなた_ホロライブ】-Dji-ehIz5_k.info.json
[debug] Invoking downloader on "https://rr7---sn-ipoxu-un5ee.googlevideo.com/videoplayback?expire=1640654639&ei=zxLKYaf7ItnHs8IPivm1oAI&ip=36.226.136.135&id=o-ACj42IOgz1K1Xjkyvak1QsGJfOPALX0biCerkdzF3Yv2&itag=303&source=youtube&requiressl=yes&mh=sC&mm=31%2C29&mn=sn-ipoxu-un5ee%2Csn-un57en7s&ms=au%2Crdu&mv=m&mvi=7&pl=25&initcwndbps=745000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1469797614&dur=3968.999&lmt=1640611016393476&mt=1640632638&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7316222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgITx9ZqaGCiYvD4vm9BNgtaQApbk3A0l01_hs4E_PGd0CIQDxh7xr7oP49WPPSE47WwLmHuZP2JDCNrbfzBEv1WCwYw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALNnZMyA_P997j-Nj8g-FjgYZTCuDaUJPsI9jLdfli8-AiEA1NwxgnSo8Ibb8ybNw1OmJlljKdPSBesMcuzsIVaOucY%3D"
[download] Destination: [20211227]【#天音かなた2周年LIVE】3D LIVE 「リベンジ」_ Amane Kanata 3DLIVE 'Revenge'【天音かな た_ホロライブ】-Dji-ehIz5_k.f303.webm
[download]   1.7% of 1.37GiB at  6.36MiB/s ETA 03:36
ERROR: Interrupted by user
```

**Comment by jim60105** [comment]
Same here. 😥
Provide my experience for your information:
[I used it in this project](https://github.com/jim60105/live-dl/blob/aafc535688be9e3c51ed9c5cff1e2e0176a4908a/live-dl#L1136-L1143)
```
yt-dlp \
        --ignore-config \
        --retries 30 \
        --merge-output-format mp4 \
        --live-from-start \
        -o "20220105 【Hollow Knight／ホロウナイト#3】メンバーシップ解禁！！実は雑談のゲーム配信！！！Ꮚ•̀ꈊ•́Ꮚ【新人Vtuber】 2022-01-06 15_05 (VnkKr5aFTZc).%(ext)s" \
        "${WEBPAGE_URL}" >> "$OUTPUT_PATH.log" 2>&1
``` 
What I got in the end:
![2022-01-06 23 47 03](https://user-images.githubusercontent.com/16995691/148411070-c03ef973-695f-4caf-9aab-855e9d3f3aaa.png)
Log file:
[20220105 【Hollow Knight／ホロウナイト#3】メンバーシップ解禁！！実は雑談のゲーム配信！！！Ꮚ•̀ꈊ•́Ꮚ【新人Vtuber】 2022-01-06 15_05 (VnkKr5aFTZc).log](https://github.com/yt-dlp/yt-dlp/files/7823046/20220105.Hollow.Knight.3.Vtuber.2022-01-06.15_05.VnkKr5aFTZc.log)

I look forward to it being fixed.

**Comment by glubsy** [comment]
Yup, experiencing this issue as well. The last fragment always fails to download, and the last merge phase of the audio and video tracks are skipped because of that.

**Comment by Rukeith** [comment]
Same issue here, is that a way or arg to fix this?

**Comment by Lesmiscore** [comment]
The last rewrite (#2870) SHOULD make them merged, at the time I wrote it
That's strange since `Did not get any data blocks`s (and 404/503 as well) has to be ignored, and I made that on the PR

**Comment by jim60105** [comment]
@Lesmiscore Thank you for your work! I confirm that this issue has been solved on my end.
It merged successfully after live stream end.

It still left two fragment files, but I was able to bypass this by `--no-part`.
I'm not sure if this is the design, or another issue.
![2022-03-29 21 29 09](https://user-images.githubusercontent.com/16995691/160665066-d78ef434-2ecd-4fbb-9fe2-8190ac0216cc.png)

**Comment by jim60105** [comment]
> I did nothing yet 😅
> The last rewrite (#2870 and [195c228](https://github.com/yt-dlp/yt-dlp/commit/195c22840c594c8f9229cb47ffec2a8984c53a0c)) SHOULD make them merged, at the time I wrote it That's strange since `Did not get any data blocks`s (and 404/503 as well) has to be ignored, and I made that on the PR

I am testing with yt-dlp version 2022.03.08.1 [c0c2c57] now. And the last time I tried `--live-from-start` and had this problem was January 7. I think this issue was already fixed at the time, but it just wasn't mentioned in this issue.

**Comment by pukkandan** [comment]
Sadly, other people have still been reporting the same issue. So does not appear to have been fully fixed

**Comment by tokon2000** [comment]
Yesterday I have recorded two live streams, both are not merged.

```
[debug] Command-line config: ['--ignore-config', '--hls-prefer-native', '--hls-use-mpegts', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--retries', '5', '--cookies', 'cookies.txt', '--no-part', '--live-from-start', '-vU', '-o', './downloads/Awakenings/20220416 Awakenings Easter Festival 2022 Stage T 2022-04-16 17_13 (VoZAYiqHHzE)', 'https://www.youtube.com/watch?v=VoZAYiqHHzE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Linux-4.4.180+-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Optional libraries: certifi, Crypto, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=VoZAYiqHHzE
[youtube] VoZAYiqHHzE: Downloading webpage
[youtube] VoZAYiqHHzE: Downloading android player API JSON
[youtube] VoZAYiqHHzE: Downloading MPD manifest
[youtube] VoZAYiqHHzE: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] VoZAYiqHHzE: Downloading 1 format(s): 299+140
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/..."
[dashsegments] Total fragments: unknown (live)
[download] Destination: ./downloads/Awakenings/20220416 Awakenings Easter Festival 2022 Stage T 2022-04-16 17_13 (VoZAYiqHHzE).f299.mp4
[dashsegments] Total fragments: unknown (live)
[download] Destination: ./downloads/Awakenings/20220416 Awakenings Easter Festival 2022 Stage T 2022-04-16 17_13 (VoZAYiqHHzE).f140.mp4

2: [download] 1.00KiB at  1.41KiB/s (00:00)
2: [download] 3.00KiB at  4.24KiB/s (00:00)
2: [download] 7.00KiB at  9.85KiB/s (00:00)
2: [download] 15.00KiB at 21.09KiB/s (00:00)
2: [download] 31.00KiB at 43.25KiB/s (00:00)
2: [download] 63.00KiB at 84.25KiB/s (00:00)
2: [download] 80.26KiB at 106.46KiB/s (00:00)
2: [download] 80.26KiB at 106.33KiB/s (00:00) (frag 1)
1: [download] 1.00KiB at  1.21KiB/s (00:00)
1: [download] 3.00KiB at  3.63KiB/s (00:00)
1: [download] 7.00KiB at  8.47KiB/s (00:00)
1: [download] 15.00KiB at 18.14KiB/s (00:00)
1: [download] 31.00KiB at 36.40KiB/s (00:00)
1: [download] 63.00KiB at 72.10KiB/s (00:00)
2: [download] 81.26KiB at  8.16KiB/s (00:00) (frag 1)
2: [download] 83.26KiB at 24.35KiB/s (00:00) (frag 1)
2: [download] 87.26KiB at 56.56KiB/s (00:00) (frag 1)
2: [download] 95.26KiB at 120.67KiB/s (00:00) (frag 1)
1: [download] 127.00KiB at 141.38KiB/s (00:00)
2: [download] 111.26KiB at 215.69KiB/s (00:00) (frag 1)
2: [download] 143.26KiB at 356.33KiB/s (00:00) (frag 1)
1: [download] 255.00KiB at 267.89KiB/s (00:00)
2: [download] 160.17KiB at 404.76KiB/s (00:00) (frag 1)
2: [download] 160.17KiB at 402.51KiB/s (00:00) (frag 2)
1: [download] 511.00KiB at 518.30KiB/s (00:00)
1: [download] 899.15KiB at 877.71KiB/s (00:01)
1: [download] 899.15KiB at 876.74KiB/s (00:01) (frag 1)
2: [download] 161.17KiB at  6.48KiB/s (00:01) (frag 2)
***
1: [download] 12.27GiB at 103.11KiB/s (05:52:47) (frag 6589)
1: [download] 12.27GiB at 148.26KiB/s (05:52:47) (frag 6589)
1: [download] 12.27GiB at 147.88KiB/s (05:52:47) (frag 6590)
1: [download] 12.27GiB at  211.43B/s (05:52:52) (frag 6590) 
1: [download] 12.27GiB at  634.22B/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at  1.45KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at  3.10KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at  6.37KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 12.88KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 25.80KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 51.50KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 102.62KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 203.31KiB/s (05:52:52) (frag 6590)
1: [download] 12.27GiB at 203.27KiB/s (05:52:52) (frag 6591)
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 1 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 2 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 3 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 4 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 5 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 6 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 7 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 8 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 9 of 10) ...

[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 6592 (attempt 10 of 10) ...
ERROR: 'fragment_filename_sanitized'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3085, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 56, in real_download
    return self.download_and_append_fragments_multiple(*args)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 433, in download_and_append_fragments_multiple
    result = result and future_result(job)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 416, in future_result
    return future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 396, in thread_func
    return self.download_and_append_fragments(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 531, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 144, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
KeyError: 'fragment_filename_sanitized'
```

**Comment by Grarie** [comment]
It's not a solution, but if anyone searches for a workaround, this way you get a playable file at least:
`ffmpeg.exe -i videofile.part' -i audiofile.part' -c:v copy -c:a copy output.mp4`

**Comment by mikelei8291** [comment]
I think this was fixed in version `2022.05.18`. The download thread would give up the last incomplete segment after a default of 10 tries and the merger would merge all the complete segments.

<details><summary>log</summary>

```
...
[download] Got server HTTP error: The read operation timed out. Retrying (attempt 1 of 10) ...

[download] 239.00MiB at  1.09KiB/s (01:57:10) (frag 5922)[download] Got server HTTP error: IncompleteRead(8125 bytes read). Retrying (attempt 2 of 10) ...
[download] 706.46MiB at  2.53KiB/s (01:57:22) (frag 5922)[download] Got server HTTP error: The read operation timed out. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: IncompleteRead(264 bytes read). Retrying (attempt 10 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 9 of 10) ...
ERROR: giving up after 10 retries
[download] fragment not found; Skipping fragment 5923 ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 5 of 10) ...
[download] Got server HTTP error: IncompleteRead(957 bytes read). Retrying (attempt 10 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 5924 ...
[download] 100% of 706.36MiB in 01:58:28ERROR: giving up after 10 retries
[download] fragment not found; Skipping fragment 5923 ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 5924 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 5924 ...

[download] 100% of 238.98MiB in 01:58:40
[Merger] Merging formats into "filename.mkv"
```
</details>

However, the last incomplete segment would not be merged into the final output and would be left as a `*-Frag<number>.part` file. Although the file would usually only be less than 1 second, it would be great if it also got merged into the output, as the content of it is still valid and playable.

**Comment by alexk-ede** [comment]
I sadly still have the issue.

> It's not a solution, but if anyone searches for a workaround, this way you get a playable file at least: `ffmpeg.exe -i videofile.part' -i audiofile.part' -c:v copy -c:a copy output.mp4`
Also, the .part files are empty for me, so ffmpeg can't do anything ...
And cat doesn't work either, as when processing, I get 'Non-monotonous DTS in output stream 0:0; ...'

**Comment by Lux-Hue** [comment]
Also having similar issues. Specifically merging goes wrong because there is invalid data in the dowloaded files.

Using ffprobe on the downloaded files also mentions the "error reading header, invalid data found when processing input" error.

`1: [download]    7.58GiB at    3.82MiB/s (04:52:53) (frag 19099/19100)
2: [download]  394.60MiB at      0.00B/s (04:52:52) (frag 19098/19100)
2: [download]  394.60MiB at      0.00B/s (04:52:57) (frag 19098/19100)
2: [download]  394.60MiB at      0.00B/s (04:52:57) (frag 19098/19100)
2: [download]  394.61MiB at      0.00B/s (04:52:57) (frag 19098/19100)
2: [download]  394.62MiB at      0.00B/s (04:52:57) (frag 19098/19100)
2: [download]  394.62MiB at      0.00B/s (04:52:57) (frag 19099/19100)
2: [download]  394.62MiB at      0.00B/s (04:52:57) (frag 19099/19100)
2: [download]  394.62MiB at      0.00B/s (04:53:08) (frag 19099/19100)
2: [download]  394.62MiB at      0.00B/s (04:53:08) (frag 19099/19100)
2: [download]  394.63MiB at      0.00B/s (04:53:08) (frag 19099/19100)
[download] Got error: HTTPSConnectionPool(host='rr1---sn-32o-bg9e.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
[download] Got error: HTTPSConnectionPool(host='rr1---sn-32o-bg9e.googlevideo.com', port=443): Read timed out.. Retrying (1/10)...
[download] Got error: HTTPSConnectionPool(host='rr1---sn-32o-bg9e.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (2/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (3/10)...
1: [download]    7.58GiB at      0.00B/s (04:52:53) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
[download] Got error: 40 bytes read. Retrying (3/10)...
[download] Got error: 42074 bytes read. Retrying (4/10)...
1: [download]    7.58GiB at      0.00B/s (04:53:40) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:57) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:57) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:57) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:53:57) (frag 19099/19100)
[download] Got error: 40 bytes read. Retrying (4/10)...
[download] Got error: 10330 bytes read. Retrying (5/10)...
1: [download]    7.58GiB at      0.00B/s (04:53:57) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:54:01) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:54:01) (frag 19099/19100)
[download] Got error: 40 bytes read. Retrying (5/10)...
[download] Got error: 3162 bytes read. Retrying (6/10)...
1: [download]    7.58GiB at      0.00B/s (04:54:01) (frag 19099/19100)
1: [download]    7.58GiB at      0.00B/s (04:54:04) (frag 19099/19100)
[download] Got error: 40 bytes read. Retrying (6/10)...
[download] Got error: 90 bytes read. Retrying (7/10)...
[download] Got error: 40 bytes read. Retrying (7/10)...
[download] Got error: 90 bytes read. Retrying (8/10)...
[download] Got error: 40 bytes read. Retrying (8/10)...
[download] Got error: 90 bytes read. Retrying (9/10)...
[download] Got error: 40 bytes read. Retrying (9/10)...
[download] Got error: 90 bytes read. Retrying (10/10)...
[download] Got error: 40 bytes read. Retrying (10/10)...
ERROR: 
[download] Got error: 90 bytes read. Giving up after 10 retries
[download] fragment not found; Skipping fragment 19100 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (3/10)...
ERROR: 
[download] Got error: 40 bytes read. Giving up after 10 retries
[download] fragment not found; Skipping fragment 19100 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (10/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (7/10)...
[download] fragment not found; Skipping fragment 19101 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 19101 (10/10)...
[youtube] _BX63y8cmtg: Downloading webpage
[youtube] _BX63y8cmtg: Downloading ios player API JSON
[youtube] _BX63y8cmtg: Downloading android player API JSON
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (1/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (2/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (3/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Giving up after 3 retries
1: [download] 100% of    7.58GiB in 04:54:36 at 449.83KiB/s
[download] fragment not found; Skipping fragment 19101 ...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (1/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (2/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Retrying (3/3)...
WARNING: [youtube] _BX63y8cmtg: Video is no longer live. Giving up after 3 retries
2: [download] 100% of  394.62MiB in 04:54:38 at 22.86KiB/s
[Merger] Merging formats into "/drives/media/Tartube Storage/griffinstreams/2023-11-19 - What's Up GAMERS...The Last of Us 2 Abbyzilla Remastered GOTY 2024, Sony is Desperate for PS5 Games.mp4"
ERROR: file:/drives/media/Tartube Storage/griffinstreams/2023-11-19 - What's Up GAMERS...The Last of Us 2 Abbyzilla Remastered GOTY 2024, Sony is Desperate for PS5 Games.f299.mp4: Invalid data found when processing input
Livestream download failed`

**Comment by tuppgallocapon** [comment]
Got the same sort of error:

yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio --merge-output-format mp4 --output "Ririka Ch - %(upload_date>%Y-%m-%d)s.%(ext)s" --embed-thumbnail --write-thumbnail --mark-watched --add-metadata --cookies-from-browser chrome --live-from-start "https://www.youtube.com/live/_2Jl1j8HNi8?si=KKrKuSdsEBnov8pT"
Extracting cookies from chrome
Extracted 3412 cookies from chrome
[youtube] Extracting URL: https://www.youtube.com/live/_2Jl1j8HNi8?si=KKrKuSdsEBnov8pT
[youtube] _2Jl1j8HNi8: Downloading webpage
[youtube] _2Jl1j8HNi8: Downloading ios player API JSON
[youtube] _2Jl1j8HNi8: Downloading android player API JSON
[youtube] _2Jl1j8HNi8: Downloading MPD manifest
[youtube] _2Jl1j8HNi8: Downloading MPD manifest
[youtube] _2Jl1j8HNi8: Marking watched
[youtube] _2Jl1j8HNi8: Marking fully watched
[info] _2Jl1j8HNi8: Downloading 1 format(s): 299+140
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: Ririka Ch - 2024-01-23.webp
[dashsegments] Total fragments: unknown (live)
[download] Destination: Ririka Ch - 2024-01-23.f299.mp4
[dashsegments] Total fragments: unknown (live)
[download] Destination: Ririka Ch - 2024-01-23.f140.mp4
[download]    4.20GiB at  137.57KiB/s (02:14:33) (frag 4072/4072)
[download]  164.33MiB at      0.00B/s (02:14:37) (frag 4072/4074)[download] Got error: HTTPSConnectionPool(host='rr2---sn-uxa0n-t35e.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/10)...
[download] Got error: HTTPSConnectionPool(host='rr1---sn-uxa0n-t8gs.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/10)...
[download]  164.34MiB at      0.00B/s (02:15:02) (frag 4072/4074)[download] Got error: HTTPSConnectionPool(host='rr1---sn-uxa0n-t8gs.googlevideo.com', port=443): Read timed out. (read timeout=20.0). Retrying (2/10)...
[download] Got error: HTTPSConnectionPool(host='rr2---sn-uxa0n-t35e.googlevideo.com', port=443): Read timed out.. Retrying (2/10)...
[download]    4.20GiB at      0.00B/s (02:15:23) (frag 4072/4074)[download] Got error: HTTP Error 503: Service Unavailable. Retrying (3/10)...


ERROR: Did not get any data blocks
[download] fragment not found; Skipping fragment 4073 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (2/10)...
[download] Got error: 602 bytes read. Retrying (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (9/10)...
[download] Got error: 602 bytes read. Retrying (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (10/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (3/10)...
[download] fragment not found; Skipping fragment 4074 ...
[youtube] _2Jl1j8HNi8: Downloading webpage
[youtube] _2Jl1j8HNi8: Downloading ios player API JSON
[youtube] _2Jl1j8HNi8: Downloading android player API JSON
[youtube] _2Jl1j8HNi8: Downloading m3u8 information
[youtube] _2Jl1j8HNi8: Downloading m3u8 information
[youtube] _2Jl1j8HNi8: Downloading MPD manifest
[youtube] _2Jl1j8HNi8: Downloading m3u8 information
[youtube] _2Jl1j8HNi8: Downloading MPD manifest

[download] 100% of  164.33MiB in 02:15:51 at 20.64KiB/s[download] Got error: 602 bytes read. Retrying (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (4/10)...
[download] Got error: 602 bytes read. Retrying (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (5/10)...
[download] Got error: 602 bytes read. Retrying (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4073 (6/10)...
[download] Got error: 602 bytes read. Retrying (1/10)...
[download] Got error: 602 bytes read. Retrying (2/10)...
[download] Got error: 602 bytes read. Retrying (3/10)...
[download] Got error: 602 bytes read. Retrying (4/10)...
[download] Got error: 602 bytes read. Retrying (5/10)...
[download] Got error: 602 bytes read. Retrying (6/10)...
[download] Got error: 602 bytes read. Retrying (7/10)...
[download] Got error: 602 bytes read. Retrying (8/10)...
[download] Got error: 602 bytes read. Retrying (9/10)...
[download] Got error: 602 bytes read. Retrying (10/10)...
[download] Got error: 602 bytes read. Giving up after 10 retries
[download] fragment not found; Skipping fragment 4073 ...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 4074 (10/10)...
[download] 100% of    4.20GiB in 02:17:32 at 534.20KiB/s

[Merger] Merging formats into "Ririka Ch - 2024-01-23.mp4"
ERROR: Postprocessing: Error opening input files: Invalid data found when processing input

**Comment by bashonly** [comment]
@tuppgallocapon upgrade to ffmpeg 6.1.1 or newer

**Comment by GGG-KILLER** [comment]
Ok, so, in my case I'm on 2023.12.30 with ffmpeg 6.1 and it still errored in a live stream.

I'm trying to concat the files afterwards with ffmpeg but it seems both the audio part and video part files got corrupted somehow:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x6bd380] error reading header
[in#0 @ 0x6bd280] Error opening input: Invalid data found when processing input                                                                                                                                                               
```

**Comment by bashonly** [comment]
ffmpeg 6.1.1 NOT ffmpeg 6.1

**Comment by purpleidea** [comment]
I can confirm this issue.

If I do a `yt-dlp` for a short amount of time and then hit `^C`, it closes the downloading gracefully, and merges the streams.

However, if I leave it for almost an hour, and indeed it has this merge issue. I got left with two files:

`something.f140.mp4` and `something.f299.mp4` (I edited the file name to something prefix)

Well I was able to manually merge with:

`ffmpeg -i something.f299.mp4 -i something.f140.mp4 -c:v copy -c:a copy output.mp4`

I got tons of warnings playing these files...

> [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Found duplicated MOOV Atom. Skipped it

And I checked the basic things, lots of disk space, etc.

```
$ yt-dlp --version
2024.03.10
```

**Comment by pukkandan** [comment]
> I got tons of warnings playing these files...
> 
> > [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Found duplicated MOOV Atom. Skipped it

When playing? or when merging? If during merging, it's expected and can be ignored

**Comment by purpleidea** [comment]
Yes when merging. Yes when playing the individual .f299 file as well.
Cheers.

**Comment by rattailgamer** [comment]
I have an interesting thing I just found out. I had/have the same problems. Since I have a bunch of old laptops laying around and a mac mini besides my Pc I decided to run some tests having them all run on the same stream with some different settings (all with --live-from-start) and see if I find something that works. long story short all Windows PCs  constantly failed while on mac it worked and I have repeated it for 4 streams now. Successfully got the stream in a .mkv 1440p60 everytime. 
so somethings seems to be different with it and makes it work. I'm fairly sure it will be the same for linux, but I will give it a try in the next couple of days when I find time. I have no clue what the reason is, but maybe one of the smart people hear can figure out the problem with windows with that info. :)
