### ISSUE TITLE
`--mark-watched` does not marks video as fully watched.

### ISSUE THREAD

**Issue by soredake** [yt-dlp/yt-dlp#2555]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`--mark-watched` only marks video as partially watched, not as fully watched:
![изображение](https://user-images.githubusercontent.com/5204968/151783204-5c6ce7b5-0262-4bdf-83ea-6c3f451197eb.png)

### Verbose log

```shell
❯ yt-dlp --cookies-from-browser firefox --mark-watched -vU https://www.youtube.com/watch?v=72zEL9iSIXo
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--mark-watched', '-vU', 'https://www.youtube.com/watch?v=72zEL9iSIXo']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\User\AppData\Roaming\Mozilla\Firefox\Profiles\ntr0heq8.default-release\cookies.sqlite"
[Cookies] Extracted 2838 cookies from firefox
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=72zEL9iSIXo
[youtube] 72zEL9iSIXo: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] 72zEL9iSIXo: Downloading android player API JSON
[debug] Loading youtube-nsig.495d0f2b from cache
[debug] [youtube] Decrypted nsig oh29N3uJm3KFv3W1yI8 => ZMKMYa1cjy1ktQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[youtube] 72zEL9iSIXo: Marking watched
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 72zEL9iSIXo: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://rr2---sn-uxoxu05-vqnl.googlevideo.com/videoplayback?expire=1643648852&ei=9ML3YYk2grfWArfViMAH&ip=31.31.99.193&id=o-ALnQi5ga-_vwDDOS1ZOFF1t2JuE939yeeq12S7XdOdkU&itag=303&source=youtube&requiressl=yes&mh=KS&mm=31%2C29&mn=sn-uxoxu05-vqnl%2Csn-3c27sne7&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=1365000&vprv=1&mime=video%2Fwebm&gir=yes&clen=47294725&dur=441.583&lmt=1617493441873642&mt=1643626843&fvip=16&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMPkW5lGL3cegXS65RYmM5G5uiOjNTm3wOd_OmFgR8lgAiEAg774cjPOLvxFKnXEQuTK40-U1TrJNyOlBCEiIRo-9B4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAINuvrZzlPGVVa8W6oE65lW4SWTGuzLgipW4I7zsJ59sAiAVECUGfiIpDomGZ75xSOG9LHajoXmovCxaeMnsRZc0Uw%3D%3D"
[download] Resuming download at byte 42706448
[download] Destination: 5 Ways Windows is Better Than Linux [72zEL9iSIXo].f303.webm
[download] 100% of 45.10MiB in 00:00
[debug] Invoking downloader on "https://rr2---sn-uxoxu05-vqnl.googlevideo.com/videoplayback?expire=1643648852&ei=9ML3YYk2grfWArfViMAH&ip=31.31.99.193&id=o-ALnQi5ga-_vwDDOS1ZOFF1t2JuE939yeeq12S7XdOdkU&itag=251&source=youtube&requiressl=yes&mh=KS&mm=31%2C29&mn=sn-uxoxu05-vqnl%2Csn-3c27sne7&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=1365000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6106418&dur=441.621&lmt=1617317228346810&mt=1643626843&fvip=16&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdnG6AA09aRID88N53Zoh5b-qjszpEsDU0Q9fi9deZQkCIQDVyqxAu36WO_a3NVpNmDLTTohImudF5NcOxFrfJLVf8Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAINuvrZzlPGVVa8W6oE65lW4SWTGuzLgipW4I7zsJ59sAiAVECUGfiIpDomGZ75xSOG9LHajoXmovCxaeMnsRZc0Uw%3D%3D"
[download] Destination: 5 Ways Windows is Better Than Linux [72zEL9iSIXo].f251.webm
[download] 100% of 5.82MiB in 00:00
[Merger] Merging formats into "5 Ways Windows is Better Than Linux [72zEL9iSIXo].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:5 Ways Windows is Better Than Linux [72zEL9iSIXo].f303.webm" -i "file:5 Ways Windows is Better Than Linux [72zEL9iSIXo].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:5 Ways Windows is Better Than Linux [72zEL9iSIXo].temp.webm"
Deleting original file 5 Ways Windows is Better Than Linux [72zEL9iSIXo].f303.webm (pass -k to keep)
Deleting original file 5 Ways Windows is Better Than Linux [72zEL9iSIXo].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
I'm pretty sure this is not possible to do

**Comment by pukkandan** [comment]
How much of a video is watched is marked by `https://s.youtube.com/api/stats/watchtime` endpoint which can be obtained with 
```py
        playback_url = get_first(
            player_responses, ('playbackTracking', 'videostatsWatchtimeUrl', 'baseUrl'),
            expected_type=url_or_none)
```

I have no clue how some of the query params are generated, and requesting without those params do not move the marker

**Comment by coletdjnz** [comment]
related: https://github.com/ytdl-org/youtube-dl/issues/18882, https://github.com/ytdl-org/youtube-dl/issues/14021, https://github.com/ytdl-org/youtube-dl/issues/15382

**Comment by soredake** [comment]
@Brett824 tried watching videos with this commit https://github.com/yt-dlp/yt-dlp/commit/06cc8f103b571380b30f03beff94d522930f64e4, videos are not marked as shorts anymore, but still doesn't marked as fully watched for me.

**Comment by pukkandan** [comment]
can repro

**Comment by bsun0000** [comment]
Broken, but can be fixed by changing 
**'st': video_length** into **'st': 0**
In extractors/youtube.py, _mark_watched routine.
Don't ask why and how it works, idk.

**Comment by pukkandan** [comment]
> Broken again. Only marks shorts.

I cant reproduce

**Comment by ddscentral** [comment]
I've tried downloading several videos, only shorts were marked. I can download my own private videos so I do think my cookie setup is fine.
Using st: 0 does indeed work to mark the video as fully watched, will leave it like that for now.

**Comment by gunir** [comment]
I believe it's broken again

```yt-dlp https://m.youtube.com/watch?v=ES6Z2IxIxKA --mark-watched --simulate --cookies-from-browser=firefox:D:\PB\Data\profilet --proxy=http://127.0.0.1:9091 -vU
[debug] Command-line config: ['https://m.youtube.com/watch?v=ES6Z2IxIxKA', '--mark-watched', '--simulate', '--cookies-from-browser=firefox:D:\\PB\\Data\\profilet', '--proxy=http://127.0.0.1:9091', '-vU']
[debug] Portable config "D:\Deve\AFProxyDev2\mpv\yt-dlp.conf": ['-o', 'D:/Deve/AFProxyDev2/mpv/dl/%(title)s.%(ext)s', '--format=bestvideo[fps<=30][ext=mp4][height<=?720]+bestaudio/worst', '--no-check-certificates', '--yes-playlist', '--write-sub', '--write-auto-sub', '--mark-watched']
Extracting cookies from firefox
[debug] Extracting cookies from: "D:\PB\Data\profilet\cookies.sqlite"
Extracted 2478 cookies from firefox
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.31.204930 [7237c8dca] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.1-1-g6d83c5f876-20220725 (setts), phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'all': 'http://127.0.0.1:9091'}
[debug] Extractor Plugins: NSigDeno (YoutubeIE)
[debug] Plugin directories: ['D:\\Deve\\AFProxyDev2\\mpv\\yt-dlp-plugins\\yt-dlp-YTNSigDeno\\yt_dlp_plugins']
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.31.204930, Current version: nightly@2023.08.31.204930
Current Build Hash: 97739c0e6cceb16eea8003b1a13016f6eda136adf68937258552b4d8f41ee5ba
yt-dlp is up to date (nightly@2023.08.31.204930)
[youtube+NSigDeno] Extracting URL: https://m.youtube.com/watch?v=ES6Z2IxIxKA
[youtube+NSigDeno] ES6Z2IxIxKA: Downloading webpage
[debug] [youtube+NSigDeno] Extracted SAPISID cookie
[youtube+NSigDeno] ES6Z2IxIxKA: Downloading ios player API JSON
[youtube+NSigDeno] ES6Z2IxIxKA: Downloading android player API JSON
[youtube+NSigDeno] ES6Z2IxIxKA: Downloading m3u8 information
WARNING: [youtube+NSigDeno] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube+NSigDeno] Incomplete data received in embedded initial data; re-fetching using API.
[youtube+NSigDeno] ES6Z2IxIxKA: Downloading initial data API JSON
[youtube+NSigDeno] ES6Z2IxIxKA: Marking watched
[youtube+NSigDeno] ES6Z2IxIxKA: Marking fully watched
[info] ES6Z2IxIxKA: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] ES6Z2IxIxKA: Downloading 1 format(s): 609+251
```

**Comment by bsun0000** [comment]
Works for me. Although youtube takes a minute or so to update the status of the video but "watched" flag/bar appears normally. I'm using yt-dlp git:876b70c8e (aug. 14), ver. 2023.07.06.

**Comment by bashonly** [comment]
> WARNING: [youtube+NSigDeno] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> WARNING: [youtube+NSigDeno] Incomplete data received in embedded initial data; re-fetching using API.

@gunir seems like it could be a consent cookie problem causing the "mark watched" request to fail. This should be fixed in nightly, but some users have reported lingering issues with it if their account's region does not match their current IP's region (I noticed you are using a proxy)

**Comment by gunir** [comment]
> > WARNING: [youtube+NSigDeno] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> > WARNING: [youtube+NSigDeno] Incomplete data received in embedded initial data; re-fetching using API.
> 
> @gunir seems like it could be a consent cookie problem causing the "mark watched" request to fail. This should be fixed in nightly, but some users have reported lingering issues with it if their account's region does not match their current IP's region. I noticed you are using a proxy, but I don't know what your situation exactly is, so I'm not able to offer any helpful suggestions without more info

My proxy is a local proxy to debug yt-dlp's requests, it doesn't do anything extra stuff in this case, but I somehow make it work again by logging out and logging in my Google Account, it happens sometimes and the solution always work.

**Comment by lukilester** [comment]
This is still happening to me in 2025. But I noticed videos longer than 20 minutes are properly getting marked as fully watched.
