### ISSUE TITLE
Downloading private embedded video from vimeo fails

### ISSUE THREAD

**Issue by J0s3f** [yt-dlp/yt-dlp#3360]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe, probably everywhere

### Description

First: If this is too similar to #2128, sorry, please close it. But because I get error 404 directly, I think it is different (or not even a bug and I am just using yt-dlp wrong)

So there is a private page, accessible by URL without login, which has a video from vimeo embedded (actually it was a live stream and now is the recording of the stream). Since it is a private link, I am willing to share it with developers/maintainers but can't post it here.

The embedded video plays fine, and if I click on the vimeo logo, a new tab opens with the video on vimeo (https://vimeo.com/[videoID]?embedded=true&source=vimeo_logo&owner=[ownerID])
Opening this link in a different Browser fails, if the page where it is embedded hasn't been opened before.

So I exported the cookies on vimeo using [this addon](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) in Brave. 
The full commandline I tried for yt-dlp is:
`yt-dlp.exe -Uv "https://vimeo.com/[videoID]?embedded=true&source=vimeo_logo&owner=[ownerID]" --referer "[SITE WHERE IT IS EMBEDDED]" --cookies cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36"`

I also tried only the referer, only cookies and different combinations without success.

From the logs, it looks like yt-dlp might extract just the ID from the URL and then try to load `https://vimeo.com/[videoID]`
This doesn't work in the browser, the URL only works with the query parameters.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://vimeo.com/[videoID]?embedded=true&source=vimeo_logo&owner=[ownerID]', '--referer', '[SITE WHERE IT IS EMBEDDED]', '--cookies', 'cookies.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2020-10-21-git-289e964873-full_build-www.gyan.dev, ffprobe 2020-10-21-git-289e964873-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [vimeo] Extracting URL: https://vimeo.com/[videoID]?embedded=true&source=vimeo_logo&owner=[ownerID]
[vimeo] [videoID]: Downloading webpage
ERROR: [vimeo] [videoID]: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\vimeo.py", line 864, in _real_extract
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
Send me the non-redacted verbose log. You can reach me on discord, reddit or by email

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/aedaa455d9874f14662023f21b254168ecd55579 may have fixed this. Can't check since the URL you gave no longer works. If it doesn't fix the issue, pls give a new working URL

**Comment by Massedil** [comment]
> https://github.com/yt-dlp/yt-dlp/commit/aedaa455d9874f14662023f21b254168ecd55579 may have fixed this. Can't check since the URL you gave no longer works. If it doesn't fix the issue, pls give a new working URL

I have a private URL that still fails to be downloaded.

> You can reach me on discord, reddit or by email

How can I contact you by email to send the URL to you ?

**Comment by pukkandan** [comment]
Contact: discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by pukkandan** [comment]
Sorry for the (extremely) delayed reply. It turns out to be an issue with embedly extractor. It has been fixed in 78d25e0b7c2b45597e193c0decb33f4f248502a9

```
❯ yt-dlp -v "https://cdn.embedly.com/widgets/media.html?src=https://player.vimeo.com/video/[redacted]?h=[redacted]&app_id=[redacted]&dntp=1&display_name=Vimeo&url=https://vimeo.com/[redacted]&key=[redacted]&type=text/html&schema=vimeo"
[debug] Command-line config: ['--ignore-config', '-v', 'https://cdn.embedly.com/widgets/media.html?src=https://player.vimeo.com/video/[redacted]?h=[redacted]&app_id=[redacted]&dntp=1&display_name=Vimeo&url=https://vimeo.com/[redacted]&key=[redacted]&type=text/html&schema=vimeo']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 78d25e0b7
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1751 extractors
[Embedly] Extracting URL: https://cdn.embedly.com/widgets/media.html?src=https://player.vimeo.com/video/[redacted]?h=[redacted]&app_id=[redacted]&dntp=1&display_name=Vimeo&url=https://vimeo.com/[redacted]&key=[redacted]&type=text/html&schema=vimeo
[vimeo] Extracting URL: https://player.vimeo.com/video/[redacted]?h=[redacted]#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fcdn.embedly.com%2Fwidgets%2Fmedia.html%3Fsrc%3Dhttps%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F[redacted]%3Fh%3D[redacted]%26app_id%3D[redacted]%26dntp%3D1%26display_name%3DVimeo%26url%3Dhttps%3A%2F%2Fvimeo.com%2F[redacted]%26key%3D[redacted]%26type%3Dtext%2Fhtml%26schema%3Dvimeo%22%7D%7D
[vimeo] [redacted]: Downloading webpage
[vimeo] [redacted]: Downloading akfire_interconnect_quic m3u8 information
[vimeo] [redacted]: Downloading akfire_interconnect_quic m3u8 information
[vimeo] [redacted]: Downloading fastly_skyfire m3u8 information
[vimeo] [redacted]: Downloading fastly_skyfire m3u8 information
[vimeo] [redacted]: Downloading akfire_interconnect_quic MPD information
[vimeo] [redacted]: Downloading akfire_interconnect_quic MPD information
[vimeo] [redacted]: Downloading fastly_skyfire MPD information
[vimeo] [redacted]: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] [redacted]: Downloading 1 format(s): dash-fastly_skyfire_sep-video-c368c1f6+dash-fastly_skyfire_sep-audio-8c7d422c
[debug] Invoking dashsegments downloader on "[redacted]"
[dashsegments] Total fragments: 870
[download] Destination: [redacted].fdash-fastly_skyfire_sep-video-c368c1f6.mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.8% of ~  30.03MiB at   59.34KiB/s ETA 05:34 (frag 7/870)
ERROR: Interrupted by user
```

**Comment by Massedil** [comment]
Thanks, I can confirm I works fine with latest release yt-dlp 2023.01.02.

**Comment by MusiCode1** [comment]
Still not working for me.
Using version 2023.01.06.
` yt-dlp.exe -v 'https://player.vimeo.com/video/700930056'`

**Comment by JimLoose** [comment]
> Still not working for me. Using version 2023.01.06. ` yt-dlp.exe -v 'https://player.vimeo.com/video/700930056'`

Confirmed: same version + problem here!
@pukkandan please reopen

**Comment by bashonly** [comment]
it's been fixed in the master branch, meaning it will be fixed in the next release. If you don't want to wait for the next release, you can use the [newest automated daily build](https://github.com/ytdl-patched/yt-dlp), or [install from master with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip)
