### ISSUE TITLE
[Broken] Download should resume even when --no-part is specified

### ISSUE THREAD

**Issue by MoodyMoon** [yt-dlp/yt-dlp#576]
## Checklist
- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
yt-dlp currently does not resume downloads if `--no-part` is specified. This does not match the behavior of youtube-dl. It would be better to follow the default behavior of youtube-dl to ease migration.

**Comment by pukkandan** [comment]
Log for reference

```
$ youtube-dl.exe tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[youtube] tf2U5Vyj0oU: Downloading player 408a20d8
[download] Destination: 42 (feat. J.Lauryn)-tf2U5Vyj0oU.f248.webm
[download]  29.5% of 20.77MiB at  2.36MiB/s ETA 00:06
ERROR: Interrupted by user

Exited with code 1 in 14.872 sec

$ youtube-dl.exe tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[download] Resuming download at byte 9920363
[download] Destination: 42 (feat. J.Lauryn)-tf2U5Vyj0oU.f248.webm
[download]  55.2% of 20.77MiB at  3.12MiB/s ETA 00:02
ERROR: Interrupted by user

Exited with code 1 in 5.013 sec

$ yt-dlp tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[youtube] tf2U5Vyj0oU: Downloading android player API JSON
[info] tf2U5Vyj0oU: Downloading 1 format(s): 248+251
[download] Destination: 42 (feat. J.Lauryn) [tf2U5Vyj0oU].f248.webm
[download]  19.3% of 20.77MiB at  3.14MiB/s ETA 00:05
ERROR: Interrupted by user

Exited with code 1 in 6.985 sec

$ yt-dlp tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[youtube] tf2U5Vyj0oU: Downloading android player API JSON
[info] tf2U5Vyj0oU: Downloading 1 format(s): 248+251
[download] 42 (feat. J.Lauryn) [tf2U5Vyj0oU].f248.webm has already been downloaded
[download] 100% of 4.00MiB
[download] Destination: 42 (feat. J.Lauryn) [tf2U5Vyj0oU].f251.webm
[download] 100% of 2.75MiB in 00:01
[Merger] Merging formats into "42 (feat. J.Lauryn) [tf2U5Vyj0oU].webm"

ERROR: Interrupted by user
```

**Comment by sdan41517** [comment]
I'm having this issue as well! Any idea when it will get fixed? youtube-dl can continue downloads even when --no-part is used.

**Comment by Vangelis66** [comment]
As I now recall, the change in the behaviour of `-c --no-part` combination (i.e. **loss of media file resumption** in a new download session) was first introduced back in the days (Jan 2021) of `youtube-dlc`, specifically in https://github.com/yt-dlp/yt-dlp/commit/0c3d0f51778b153f65c21906031c2e091fcfb641 (see also https://github.com/ytdl-org/youtube-dl/pull/20405); that's when I first noticed it and meant to report it (hence I have that culprit commit stored in my "records"), alas I never did 😞 ...

**Resuming was broken** because the default is `--no-force-overwrites` [Do not overwrite the video, but overwrite related files] and when `-c --no-part` is used, the partial media file has the exact filename as the end (completed) media file (at least that's how **I** understood things back then 😉 ... ) .

**Comment by pukkandan** [comment]
Yes, @Vangelis66 that was indeed the issue. But now all combinations of overwrites, continue and no-part should be working as expected

**Comment by MoodyMoon** [comment]
I just tried it with build `2021.08.10` and it is still not working. I have to append `.part` manually to make it work just like before.

**Comment by pukkandan** [comment]
Works for me
```
$ yt-dlp tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[youtube] tf2U5Vyj0oU: Downloading android player API JSON
[info] tf2U5Vyj0oU: Downloading 1 format(s): 248+251
[download] Destination: 42 (feat. J.Lauryn) [tf2U5Vyj0oU].f248.webm
[download]  48.6% of 20.77MiB at  3.20MiB/s ETA 00:03
ERROR: Interrupted by user

Exited with code 1 in 53.060 sec

$ yt-dlp tf2U5Vyj0oU -c --no-part
[youtube] tf2U5Vyj0oU: Downloading webpage
[youtube] tf2U5Vyj0oU: Downloading android player API JSON
[info] tf2U5Vyj0oU: Downloading 1 format(s): 248+251
[download] Resuming download at byte 10584394
[download] Destination: 42 (feat. J.Lauryn) [tf2U5Vyj0oU].f248.webm
[download]  58.2% of 20.77MiB at  3.28MiB/s ETA 00:02
ERROR: Interrupted by user

Exited with code 1 in 7.434 sec
```

**Comment by MoodyMoon** [comment]
I feel like I am not giving enough information thus making it hard to debug so I will try to elaborate more here.
I am using Windows and it seems like it is only happening on Windows since I am guessing you are using Linux (the `$` symbol in front of the command).
It seems that it does not matter whether or not `-c` or `--continue` is specified since it is the default behavior according to `README.md`. I did tried it with `--continue` specified but it still does not work.

Here is the command I used
`"<path to prebuilt x64 exe>" --buffer-size "10M" --continue --no-part --no-cache-dir -o "<format>" -f 136 <url>`

**Comment by pukkandan** [comment]
@MoodyMoon Show your verbose logs. I cant reproduce the issue irrespective of the OS

**Comment by MoodyMoon** [comment]
```
[debug] Command-line config: ['--verbose', '--continue', '--no-part', '--buffer-size', '10M', '--no-cache-dir', '-o', 'Z:\\%(title)s.%(ext)s', '-f', '136', 'https://www.youtube.com/watch?v=A1WbbilfrGk']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=A1WbbilfrGk
[youtube] A1WbbilfrGk: Downloading webpage
[youtube] A1WbbilfrGk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[info] A1WbbilfrGk: Downloading 1 format(s): 136
[debug] Invoking downloader on "https://r8---sn-uh-c3pl.googlevideo.com/videoplayback?expire=1628884202&ei=ingWYdaFIYHK4-EPzdaWkAc&ip=60.48.172.169&id=o-AFG05UlEYjsblSq2DCcYKWZ_Ooauh9LcSfHMGu9q1WGt&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mh=Lq&mm=31%2C29&mn=sn-uh-c3pl%2Csn-30a7rn7z&ms=au%2Crdu&mv=m&mvi=8&pl=23&initcwndbps=296250&vprv=1&mime=video%2Fmp4&ns=wuQFv4LtbSkr_x19L7k1W2MG&gir=yes&clen=821320756&dur=4418.966&lmt=1575048751022681&mt=1628861598&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5316222&n=eQKMwZwnXJ2P7b4I-ho&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMSfBaN52NS07-9ayVkVzk4R2fbpEmhUeqYmdBcOEAxxAiEAuMfH-wUJxjT3a3Cf3TpNYGtxH22wH_9ZZyzLMH4JfkM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPVoFOL80Qo4PmCAU3RffNn7TJnwAUc9QVgqIGIz7Ba1AiEAwvjcMVKAxPx4sYYpR4yEBbQ1jOTIVQnKmEv_AjQglFE%3D"
[download] Destination: Z:\The Immigrants! - Let's Play Frostpunk HARD - Ep.3.mp4
[download]   1.2% of 783.27MiB at 155.23KiB/s ETA 01:25:03
ERROR: Interrupted by user

[debug] Command-line config: ['--verbose', '--continue', '--no-part', '--buffer-size', '10M', '--no-cache-dir', '-o', 'Z:\\%(title)s.%(ext)s', '-f', '136', 'https://www.youtube.com/watch?v=A1WbbilfrGk']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=A1WbbilfrGk
[youtube] A1WbbilfrGk: Downloading webpage
[youtube] A1WbbilfrGk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[info] A1WbbilfrGk: Downloading 1 format(s): 136
[download] Z:\The Immigrants! - Let's Play Frostpunk HARD - Ep.3.mp4 has already been downloaded
```

**Comment by pukkandan** [comment]
I see now that the issue still exists when downloading single formats. I was always testing with video+audio - so didnt notice.

**Comment by ahm750** [comment]
I compiled the binary with the latest commit and the issue still exists unfortunately :(

**Comment by ahm750** [comment]
How can I download the project with the latest commits?

**Comment by pukkandan** [comment]
`python3 -m pip install --upgrade git+https://github.com/yt-dlp/yt-dlp`
