### ISSUE TITLE
Yt-dlp is not downloading Facebook videos anymore

### ISSUE THREAD

**Issue by pibolito** [yt-dlp/yt-dlp#9105]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Since some time now (a few days) I am not able to download facebook videos (watch and reels) using yt-dlp.
I updated yt-dlp version to **2023.11.16** one.

Maybe Facebook changed something, no?
I get a parsing error.
Would it be a reason having python version 3.7 instead of 3.8? 
I had 3.7 and it used to work.

I would appreciate any help.
Thank you very much in advance
Best regards
Pibolito

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ **yt-dlp -v -f 22 "https://www.facebook.com/watch?v=281995478207345" -o "video.%(ext)s"**
[debug] Command-line config: ['-v', '-f', '22', 'https://www.facebook.com/watch?v=281995478207345', '-o', 'video.%(ext)s']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.7.1 (CPython x86_64 64bit) - Linux-3.10.0-1160.102.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.13, ffprobe 3.4.13
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.47.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[facebook] Extracting URL: https://www.facebook.com/watch?v=281995478207345
[facebook] 281995478207345: Downloading webpage
[facebook] 281995478207345: Downloading webpage
ERROR: [facebook] 281995478207345: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/facebook.py", line 752, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/facebook.py", line 697, in _extract_from_url
    raise ExtractorError('**Cannot parse data**')
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)

You are using an outdated version. This has been fixed.

> Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
>                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above

if you are unable to update your system's Python beyond 3.7, then use the [linux standalone executable](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux)

**Comment by pibolito** [comment]
Hello. 
I tried with last linux stand alone version and I still get the same error:
**ERROR: [facebook] 1375733483315678: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q=**
If I was blocked by Facebook, I guess the message wouldn't be that one, right?

How can I know if Facebook blocked me?
What else can I do to solve the problem?

Thank you very much once again

**Comment by bashonly** [comment]
> If I was blocked by Facebook, I guess the message wouldn't be that one, right?

That message is emitted by the extractor for just about any possible error (the extractor was not well thought out in this regard). So yes, that would be the message

**Comment by bashonly** [comment]
> How can I know if Facebook blocked me?

Check if the URL playable in a browser with the same IP and same login details.

I can download your URL without issue with yt-dlp

**Comment by bashonly** [comment]
> `-f 22`

Also, do not add this to your command. That format id does not exist with facebook videos. It is unrelated to your current issue, but if you get past the "cannot parse data" error, it would be the cause of a new error.

**Comment by pibolito** [comment]
Hello

Thanks for the help and the correction!
I normally use -f hd or -f sd for facebook and up till 15 days ago was working fine for facebook watch and facebook reels.

Now, I got his error:

$ yt-dlp -f hd https://www.facebook.com/reel/1375733483315678
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1375733483315678
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1375733483315678&_rdr
[facebook] 1375733483315678: Downloading webpage
[facebook] 1375733483315678: Downloading webpage
ERROR: [facebook] 1375733483315678: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -


Yesterday I ended up updating python 3.7 to python 3.8 and installed the last yt-dlp version as it can be proved using the yt-dlp command bellow:

$ yt-dlp -U
Latest version: ***@***.*** from yt-dlp/yt-dlp
yt-dlp is up to date ***@***.*** from yt-dlp/yt-dlp)

I guess it can only be because of the blocking 😕
Don't know what to do anymore to solve this problem. Do you have any extra suggestion?

Thank you and best regards
Pibolito
________________________________

**Comment by pibolito** [comment]
Hello again and sorry to disturb you once more.

I don't seem to figure out what the problem is but I find it strange Facebook blocks me knowing I don't download videos that often.

I made another test using verbose

[facebook:reel] Extracting URL: https://www.facebook.com/reel/1375733483315678
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1375733483315678&_rdr
[facebook] 1375733483315678: Downloading webpage
[facebook] 1375733483315678: Downloading webpage
ERROR: [facebook] 1375733483315678: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/facebook.py", line 795, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/extractor/facebook.py", line 740, in _extract_from_url
    raise ExtractorError('Cannot parse data')

Using yt-dlp_linux version witn -vU parameter I get the same error:
File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/facebook.py", line 795, in _real_extract
  File "yt_dlp/extractor/facebook.py", line 740, in _extract_from_url

It seems the problem is with yt-dlp code but I am using the last version what is even more strange.
I wonder if it can be a compatibility problem with another program?
Could you please verify those code lines?

Thank you and kind regards
Pibolito

________________________________

**Comment by pibolito** [comment]
Hello

I guess you were right!
I complained to Facebook about the blocking.
They  didn't reply but maybe they fixed it because for3 days I have normal access.
Thank you once more for your help and kind regards.

Pibolito


________________________________
