### ISSUE TITLE
[TikTok] No video formats found!

### ISSUE THREAD

**Issue by erikschul** [yt-dlp/yt-dlp#9532]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

Video works in the browser, but yt-dlp fails with `No video formats found!`

https://www.tiktok.com/@/video/7324026710859517189/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@/video/7324026710859517189/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds (linux_aarch64_exe)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.15.0-100-generic-aarch64-with-glibc2.17 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.36)
[debug] exe versions: ffmpeg 6.1.1-2 (setts), ffprobe 6.1.1-2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.22.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds)
[TikTok] Extracting URL: https://www.tiktok.com/@/video/7324026710859517189/
[TikTok] 7324026710859517189: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7324026710859517189: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7324026710859517189: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7324026710859517189: Downloading video feed
WARNING: [TikTok] 7324026710859517189: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
[TikTok] 7324026710859517189: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Extractor gave empty title. Creating a generic title
ERROR: [TikTok] 7324026710859517189: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1820, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2808, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1103, in raise_no_formats
yt_dlp.utils.ExtractorError: [TikTok] 7324026710859517189: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/9506

**Comment by pukkandan** [comment]
On second look, this may be a slightly different issue. Do we want to track these separately, @bashonly ?

**Comment by bashonly** [comment]
this is a hybrid dupe of #8678 and #9506

"no video formats found" only occurs when the video is only available via API due to it being flagged as sensitive / nsfw or its audio has been taken down etc, because our API access is broken rn

**Comment by erikschul** [comment]
@bashonly 

Maybe this case is different?

I'm able to access the video through the browser, with video, and the content doesn't seem to be sensitive/nsfw or have it's audio taken down.

**Comment by bashonly** [comment]
@erikschul has been fixed by cb61e20c266facabb7a30f9ce53bd79dfc158475

**Comment by ForxBase** [comment]
@bashonly the issue still persists, videos without audio are not downloaded: ERROR: [TikTok] 7200883500512382254: No video formats found!

**Comment by bashonly** [comment]
@ForxBase yep it's being tracked in #8678

if you have a working install id (`iid`) you can access the mobile API formats with `--extractor-arg "tiktok:app_info=IID"` , where `IID` is the actual install id

**Comment by soccerwithag** [comment]
How do you obtain a install id?
